/**
 * @fileoverview gRPC-Web generated client stub for greet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.1
// source: greet.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.greet = require('./greet_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.greet.GreeterClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.greet.GreeterPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.SearchUserRequest,
 *   !proto.greet.SearchUserResponse>}
 */
const methodDescriptor_Greeter_SearchUser = new grpc.web.MethodDescriptor(
  '/greet.Greeter/SearchUser',
  grpc.web.MethodType.UNARY,
  proto.greet.SearchUserRequest,
  proto.greet.SearchUserResponse,
  /**
   * @param {!proto.greet.SearchUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.SearchUserResponse.deserializeBinary
);


/**
 * @param {!proto.greet.SearchUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.greet.SearchUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.greet.SearchUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.searchUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/greet.Greeter/SearchUser',
      request,
      metadata || {},
      methodDescriptor_Greeter_SearchUser,
      callback);
};


/**
 * @param {!proto.greet.SearchUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.greet.SearchUserResponse>}
 *     Promise that resolves to the response
 */
proto.greet.GreeterPromiseClient.prototype.searchUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/greet.Greeter/SearchUser',
      request,
      metadata || {},
      methodDescriptor_Greeter_SearchUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.UserRequest,
 *   !proto.greet.UserResponse>}
 */
const methodDescriptor_Greeter_GetUsers = new grpc.web.MethodDescriptor(
  '/greet.Greeter/GetUsers',
  grpc.web.MethodType.UNARY,
  proto.greet.UserRequest,
  proto.greet.UserResponse,
  /**
   * @param {!proto.greet.UserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.UserResponse.deserializeBinary
);


/**
 * @param {!proto.greet.UserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.greet.UserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.greet.UserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.getUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/greet.Greeter/GetUsers',
      request,
      metadata || {},
      methodDescriptor_Greeter_GetUsers,
      callback);
};


/**
 * @param {!proto.greet.UserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.greet.UserResponse>}
 *     Promise that resolves to the response
 */
proto.greet.GreeterPromiseClient.prototype.getUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/greet.Greeter/GetUsers',
      request,
      metadata || {},
      methodDescriptor_Greeter_GetUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.UrlRequest,
 *   !proto.greet.UrlResponse>}
 */
const methodDescriptor_Greeter_AddUrl = new grpc.web.MethodDescriptor(
  '/greet.Greeter/AddUrl',
  grpc.web.MethodType.UNARY,
  proto.greet.UrlRequest,
  proto.greet.UrlResponse,
  /**
   * @param {!proto.greet.UrlRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.UrlResponse.deserializeBinary
);


/**
 * @param {!proto.greet.UrlRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.greet.UrlResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.greet.UrlResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.addUrl =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/greet.Greeter/AddUrl',
      request,
      metadata || {},
      methodDescriptor_Greeter_AddUrl,
      callback);
};


/**
 * @param {!proto.greet.UrlRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.greet.UrlResponse>}
 *     Promise that resolves to the response
 */
proto.greet.GreeterPromiseClient.prototype.addUrl =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/greet.Greeter/AddUrl',
      request,
      metadata || {},
      methodDescriptor_Greeter_AddUrl);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greet.NumRequest,
 *   !proto.greet.NumResponse>}
 */
const methodDescriptor_Greeter_AddNum = new grpc.web.MethodDescriptor(
  '/greet.Greeter/AddNum',
  grpc.web.MethodType.UNARY,
  proto.greet.NumRequest,
  proto.greet.NumResponse,
  /**
   * @param {!proto.greet.NumRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greet.NumResponse.deserializeBinary
);


/**
 * @param {!proto.greet.NumRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.greet.NumResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.greet.NumResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.greet.GreeterClient.prototype.addNum =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/greet.Greeter/AddNum',
      request,
      metadata || {},
      methodDescriptor_Greeter_AddNum,
      callback);
};


/**
 * @param {!proto.greet.NumRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.greet.NumResponse>}
 *     Promise that resolves to the response
 */
proto.greet.GreeterPromiseClient.prototype.addNum =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/greet.Greeter/AddNum',
      request,
      metadata || {},
      methodDescriptor_Greeter_AddNum);
};


module.exports = proto.greet;

